'use client';
import { useEffect,useState } from 'react';
import { useParams,useSearchParams } from 'next/navigation';
import FreshnessBadge from '@/components/ui/FreshnessBadge';
import type { DataSourceMeta,MarketAnalysisResponse,SecurityEvent } from '@/types';

export default function Stock360Page(){
 const {ticker}=useParams<{ticker:string}>(); const search=useSearchParams(); const exchange=search.get('exchange')||'NAS';
 const [analysis,setAnalysis]=useState<MarketAnalysisResponse|null>(null); const [meta,setMeta]=useState<DataSourceMeta|null>(null); const [events,setEvents]=useState<SecurityEvent[]>([]); const [error,setError]=useState('');
 useEffect(()=>{fetch(`/api/market-data?ticker=${encodeURIComponent(ticker)}&exchange=${exchange}`).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.message);setAnalysis(p.data||p);setMeta(p.meta||null);setError('')}).catch(e=>setError(e.message));fetch(`/api/security-events?ticker=${encodeURIComponent(ticker)}&exchange=${exchange}`).then(r=>r.json()).then(p=>setEvents(p.data||[])).catch(()=>setEvents([]))},[ticker,exchange]);
 const latest=analysis?.priceData?.at(-1); const rs=analysis?.sepaEvidence?.metrics?.rsRating; const vcp=analysis?.vcpAnalysis;
 return <div className="space-y-5 pb-12"><section className="panel-grid p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-emerald-300">Stock 360</p><h1 className="mt-1 text-3xl font-black">{ticker}</h1><p className="text-sm text-[var(--text-secondary)]">{exchange} · 가격, 추세, 리스크, 공시를 한 화면에서 확인합니다.</p></div>{meta&&<FreshnessBadge meta={meta}/>}</div>{error&&<p className="mt-5 text-rose-300">{error}</p>}</section>
 {analysis&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['현재가',latest?.close?.toLocaleString()||'-'],['RS Rating',rs??'-'],['VCP',`${vcp?.grade||'-'} / ${vcp?.score??'-'}`],['피벗',vcp?.pivotPrice?.toLocaleString()||'-']].map(([k,v])=><div key={String(k)} className="panel-grid p-5"><p className="text-xs text-[var(--text-tertiary)]">{k}</p><p className="mt-2 font-mono text-2xl font-bold">{v}</p></div>)}</section><section className="panel-grid p-5"><h2 className="font-bold">투자 체크</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><p>SEPA <b>{analysis.sepaEvidence?.status}</b></p><p>손절가 <b>{analysis.riskPlan?.stopLossPrice?.toLocaleString()||'-'}</b></p><p>진입가 <b>{analysis.riskPlan?.entryPrice?.toLocaleString()||'-'}</b></p></div>{analysis.warnings?.length>0&&<ul className="mt-4 text-xs text-amber-200">{analysis.warnings.map(x=><li key={x}>· {x}</li>)}</ul>}</section></>}
 <section className="panel-grid p-5"><h2 className="font-bold">공시·실적 이벤트 리스크</h2>{events.length?<div className="mt-3 space-y-2">{events.map(e=><a key={e.external_id} href={e.source_url||'#'} target="_blank" rel="noreferrer" className="block rounded-xl border border-[var(--border)] p-3 hover:border-emerald-400/30"><span className="text-xs text-amber-200">{e.source} · {new Date(e.occurred_at).toLocaleDateString('ko-KR')}</span><p className="mt-1 text-sm">{e.title}</p></a>)}</div>:<p className="mt-3 text-sm text-[var(--text-tertiary)]">최근 중요 이벤트가 없거나 원천 API가 설정되지 않았습니다.</p>}</section></div>;
}
