import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const workflow = readFileSync(new URL('../.github/workflows/db-backup.yml', import.meta.url), 'utf8');
const backupScript = readFileSync(new URL('../scripts/backup-supabase-encrypted.sh', import.meta.url), 'utf8');
const compatibilitySql = readFileSync(new URL('../scripts/restore-drill-supabase-compat.sql', import.meta.url), 'utf8');

assert.match(workflow, /MTN_BACKUP_AGE_RECIPIENT/);
assert.match(workflow, /postgresql-client-17/);
assert.match(workflow, /MTN_POSTGRES_BIN_DIR:\s*\/usr\/lib\/postgresql\/17\/bin/);
assert.match(workflow, /backup-supabase-encrypted\.sh/);
assert.match(workflow, /\.dump\.age/);
assert.match(workflow, /RESTORE_DRILL_DATABASE_URL/);
assert.match(workflow, /MTN_RESTORE_DRILL_CONFIRM:\s*EMPTY_TARGET_ONLY/);
assert.match(workflow, /operations_backup_runs/);
assert.match(workflow, /SUPABASE_SERVICE_ROLE_KEY/);
assert.match(workflow, /concurrency:/);
assert.match(workflow, /cancel-in-progress:\s*false/);
assert.match(workflow, /R2_ENDPOINT_URL/);
assert.match(workflow, /R2_BUCKET_NAME/);
assert.match(workflow, /R2_BACKUP_PREFIX/);
assert.match(workflow, /R2_ACCESS_KEY_ID/);
assert.match(workflow, /R2_SECRET_ACCESS_KEY/);
assert.match(workflow, /r2-backup-retention\.mjs retention --apply-retention/);
assert.match(workflow, /r2-backup-retention\.mjs plan-upload/);
assert.match(workflow, /r2-backup-retention\.mjs upload/);
assert.match(workflow, /storage_provider:\s*"R2"/);
assert.match(workflow, /if:\s*failure\(\)/);
assert.match(workflow, /status:\s*"FAILED"/);
assert.doesNotMatch(workflow, /^\s+mtn\.dump\s*$/m);
assert.doesNotMatch(workflow, /^\s+mtn\.restore-list\.txt\s*$/m);

assert.match(backupScript, /mktemp -d/);
assert.match(backupScript, /MTN_POSTGRES_BIN_DIR/);
assert.match(backupScript, /pg_dump/);
assert.match(backupScript, /write-pg-service-file\.mjs/);
assert.match(backupScript, /PGSERVICEFILE/);
assert.match(backupScript, /PGPASSFILE/);
assert.match(backupScript, /SOURCE_DB_SERVICE='service=mtn_backup_source'/);
assert.match(backupScript, /unset DATABASE_URL/);
assert.doesNotMatch(backupScript, /"\$PG_DUMP_BIN" "\$DATABASE_URL"/);
assert.doesNotMatch(backupScript, /"\$PSQL_BIN" "\$DATABASE_URL"/);
assert.match(backupScript, /PG_RESTORE_BIN[^\n]*--list/);
assert.match(backupScript, /PG_RESTORE_BIN[\s\S]{0,120}--exit-on-error/);
assert.match(backupScript, /pg_export_snapshot/);
assert.match(backupScript, /set local statement_timeout = 0/i);
assert.match(backupScript, /--snapshot=/);
assert.match(backupScript, /--schema=public/);
assert.match(backupScript, /--schema=mtn_internal/);
assert.match(backupScript, /transaction isolation level repeatable read read only/i);
assert.match(backupScript, /collect_public_row_counts/);
assert.match(backupScript, /relation\.relkind in \('r', 'p'\)/);
assert.match(backupScript, /cmp -s "\$SOURCE_ROWS_PATH" "\$RESTORED_ROWS_PATH"/);
assert.match(backupScript, /Restore drill row-count reconciliation failed/);
assert.match(backupScript, /mtn_restore_drill/);
assert.match(backupScript, /--clean/);
assert.match(backupScript, /--if-exists/);
assert.match(backupScript, /--section=pre-data/);
assert.match(backupScript, /--section=data/);
assert.match(backupScript, /--section=post-data/);
assert.match(backupScript, /age[^\n]*--recipient/);
assert.match(backupScript, /DRY_RUN/);
assert.match(backupScript, /\.dump\.age/);
assert.doesNotMatch(backupScript, /echo[^\n]*DATABASE_URL/);

assert.match(compatibilitySql, /create schema if not exists extensions/i);
assert.match(compatibilitySql, /create extension if not exists "uuid-ossp"/i);
assert.match(compatibilitySql, /create table if not exists auth\.users/i);
assert.match(compatibilitySql, /create role authenticated/i);
assert.match(compatibilitySql, /create role service_role/i);
assert.match(compatibilitySql, /column_name = 'user_id'/i);

console.log('free infrastructure backup tests passed');
