import assert from 'node:assert/strict';
import { createSharedClientRead } from '../lib/shared-client-read.ts';
let calls = 0, release, upstream;
const read = createSharedClientRead((_url, options) => {
  calls++; upstream = options.signal;
  return new Promise(resolve => { release = resolve; });
});
const first = new AbortController();
const second = new AbortController();
const a = read('/api/macro', { signal: first.signal });
const rejected = assert.rejects(a, { name: 'AbortError' });
const b = read('/api/macro', { signal: second.signal });
assert.equal(calls, 1);
first.abort();
await rejected;
assert.equal(upstream.aborted, false, 'another reader still needs the request');
release(Response.json({ asOf: '2026-09-08' }));
assert.deepEqual(await (await b).json(), { asOf: '2026-09-08' });
const third = new AbortController();
const c = read('/api/macro', { signal: third.signal });
const cancelled = assert.rejects(c, { name: 'AbortError' });
third.abort();
await cancelled;
assert.equal(upstream.aborted, true);
let clock = 0, cachedCalls = 0;
const cached = createSharedClientRead(async url => { cachedCalls++; return Response.json({ url, asOf: 'original' }); }, () => clock);
assert.deepEqual(await (await cached('/api/macro', { ttlMs: 100 })).json(), { url: '/api/macro', asOf: 'original' });
await (await cached('/api/macro', { ttlMs: 100 })).json();
assert.equal(cachedCalls, 1);
await cached('/api/macro?market=KR', { ttlMs: 100 });
assert.equal(cachedCalls, 2, 'markets must never share a response');
clock = 101;
await cached('/api/macro', { ttlMs: 100 });
assert.equal(cachedCalls, 3);
let failures = 0;
const failed = createSharedClientRead(async () => { failures++; return new Response('', { status: 503 }); });
await failed('/api/macro', { ttlMs: 100 });
await failed('/api/macro', { ttlMs: 100 });
assert.equal(failures, 2, 'failed responses must not be cached');
console.log('shared-client-read tests passed');
