// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/local-analysis" | "/beauty-contest" | "/canslim" | "/contest" | "/cross-check" | "/guide" | "/history" | "/history/[tradeId]" | "/leader" | "/links" | "/login" | "/macro" | "/master-filter" | "/momentum" | "/plan" | "/portfolio" | "/qullamaggie" | "/recommendations" | "/reversal" | "/scanner" | "/stock/[ticker]" | "/watchlist"
type AppRouteHandlerRoutes = "/api/admin/cache/clear" | "/api/admin/dart/cache-status" | "/api/admin/dart/fallback" | "/api/admin/dart/sync" | "/api/admin/data-health" | "/api/admin/us/cache-status" | "/api/admin/us/sync" | "/api/alert-events" | "/api/alert-rules" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/session" | "/api/contest/candidates/[id]" | "/api/contest/reviews" | "/api/contest/sessions" | "/api/contest/sessions/[id]" | "/api/contest/sessions/[id]/analyze" | "/api/contest/sessions/[id]/ib-validate" | "/api/contest/sessions/[id]/llm-result" | "/api/cron/chart-analysis" | "/api/cron/check-alerts" | "/api/cron/contest-review-kr" | "/api/cron/contest-review-us" | "/api/cron/daily-screeners" | "/api/cron/edgar-backfill" | "/api/cron/purge-metrics" | "/api/cron/recommendation-performance" | "/api/cron/recommendation-weekly" | "/api/cron/rs-metrics" | "/api/cron/snapshot-market-state" | "/api/local-analysis/jobs" | "/api/local-analysis/status" | "/api/local-llm-proxy/[...path]" | "/api/macro" | "/api/macro/history" | "/api/market-data" | "/api/master-filter" | "/api/master-filter/history" | "/api/performance" | "/api/portfolio/risk" | "/api/portfolio/risk/what-if" | "/api/price-history/[ticker]" | "/api/recommendations" | "/api/recommendations/diagnostics" | "/api/recommendations/metrics" | "/api/recommendations/summary" | "/api/resources" | "/api/saved-screens" | "/api/scanner/batch" | "/api/scanner/canslim" | "/api/scanner/leader" | "/api/scanner/metrics" | "/api/scanner/momentum" | "/api/scanner/qullamaggie" | "/api/scanner/reversal" | "/api/scanner/snapshots" | "/api/scanner/telegram" | "/api/scanner/universe" | "/api/security-events" | "/api/security-lookup" | "/api/security-lookup/batch" | "/api/security-search" | "/api/telegram-webhook" | "/api/test-report" | "/api/test/telegram" | "/api/toss-proxy/holdings" | "/api/trade-executions" | "/api/trade-exit-rules" | "/api/trade-stop-events" | "/api/trades" | "/api/watchlist"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/local-analysis": {}
  "/api/admin/cache/clear": {}
  "/api/admin/dart/cache-status": {}
  "/api/admin/dart/fallback": {}
  "/api/admin/dart/sync": {}
  "/api/admin/data-health": {}
  "/api/admin/us/cache-status": {}
  "/api/admin/us/sync": {}
  "/api/alert-events": {}
  "/api/alert-rules": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/session": {}
  "/api/contest/candidates/[id]": { "id": string; }
  "/api/contest/reviews": {}
  "/api/contest/sessions": {}
  "/api/contest/sessions/[id]": { "id": string; }
  "/api/contest/sessions/[id]/analyze": { "id": string; }
  "/api/contest/sessions/[id]/ib-validate": { "id": string; }
  "/api/contest/sessions/[id]/llm-result": { "id": string; }
  "/api/cron/chart-analysis": {}
  "/api/cron/check-alerts": {}
  "/api/cron/contest-review-kr": {}
  "/api/cron/contest-review-us": {}
  "/api/cron/daily-screeners": {}
  "/api/cron/edgar-backfill": {}
  "/api/cron/purge-metrics": {}
  "/api/cron/recommendation-performance": {}
  "/api/cron/recommendation-weekly": {}
  "/api/cron/rs-metrics": {}
  "/api/cron/snapshot-market-state": {}
  "/api/local-analysis/jobs": {}
  "/api/local-analysis/status": {}
  "/api/local-llm-proxy/[...path]": { "path": string[]; }
  "/api/macro": {}
  "/api/macro/history": {}
  "/api/market-data": {}
  "/api/master-filter": {}
  "/api/master-filter/history": {}
  "/api/performance": {}
  "/api/portfolio/risk": {}
  "/api/portfolio/risk/what-if": {}
  "/api/price-history/[ticker]": { "ticker": string; }
  "/api/recommendations": {}
  "/api/recommendations/diagnostics": {}
  "/api/recommendations/metrics": {}
  "/api/recommendations/summary": {}
  "/api/resources": {}
  "/api/saved-screens": {}
  "/api/scanner/batch": {}
  "/api/scanner/canslim": {}
  "/api/scanner/leader": {}
  "/api/scanner/metrics": {}
  "/api/scanner/momentum": {}
  "/api/scanner/qullamaggie": {}
  "/api/scanner/reversal": {}
  "/api/scanner/snapshots": {}
  "/api/scanner/telegram": {}
  "/api/scanner/universe": {}
  "/api/security-events": {}
  "/api/security-lookup": {}
  "/api/security-lookup/batch": {}
  "/api/security-search": {}
  "/api/telegram-webhook": {}
  "/api/test-report": {}
  "/api/test/telegram": {}
  "/api/toss-proxy/holdings": {}
  "/api/trade-executions": {}
  "/api/trade-exit-rules": {}
  "/api/trade-stop-events": {}
  "/api/trades": {}
  "/api/watchlist": {}
  "/beauty-contest": {}
  "/canslim": {}
  "/contest": {}
  "/cross-check": {}
  "/guide": {}
  "/history": {}
  "/history/[tradeId]": { "tradeId": string; }
  "/leader": {}
  "/links": {}
  "/login": {}
  "/macro": {}
  "/master-filter": {}
  "/momentum": {}
  "/plan": {}
  "/portfolio": {}
  "/qullamaggie": {}
  "/recommendations": {}
  "/reversal": {}
  "/scanner": {}
  "/stock/[ticker]": { "ticker": string; }
  "/watchlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
