// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../app/(dashboard)/canslim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/canslim">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/canslim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/contest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contest">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/contest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/cross-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cross-check">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/cross-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/leader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leader">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/leader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/momentum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/momentum">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/momentum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/qullamaggie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qullamaggie">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/qullamaggie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/reversal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reversal">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/reversal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(dashboard)/watchlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watchlist">> = Specific
  const handler = {} as typeof import("../../../../app/(dashboard)/watchlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/admin/local-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/local-analysis">> = Specific
  const handler = {} as typeof import("../../../../app/admin/local-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/beauty-contest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beauty-contest">> = Specific
  const handler = {} as typeof import("../../../../app/beauty-contest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../../../app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/history/[tradeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history/[tradeId]">> = Specific
  const handler = {} as typeof import("../../../../app/history/[tradeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../../app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/links">> = Specific
  const handler = {} as typeof import("../../../../app/links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/macro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/macro">> = Specific
  const handler = {} as typeof import("../../../../app/macro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/master-filter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-filter">> = Specific
  const handler = {} as typeof import("../../../../app/master-filter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plan">> = Specific
  const handler = {} as typeof import("../../../../app/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../../app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recommendations">> = Specific
  const handler = {} as typeof import("../../../../app/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/scanner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scanner">> = Specific
  const handler = {} as typeof import("../../../../app/scanner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/stock/[ticker]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/[ticker]">> = Specific
  const handler = {} as typeof import("../../../../app/stock/[ticker]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/cache/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cache/clear">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/cache/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/dart/cache-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dart/cache-status">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/dart/cache-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/dart/fallback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dart/fallback">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/dart/fallback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/dart/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dart/sync">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/dart/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/data-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/data-health">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/data-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/us/cache-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/us/cache-status">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/us/cache-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/admin/us/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/us/sync">> = Specific
  const handler = {} as typeof import("../../../../app/api/admin/us/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/alert-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alert-events">> = Specific
  const handler = {} as typeof import("../../../../app/api/alert-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/alert-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alert-rules">> = Specific
  const handler = {} as typeof import("../../../../app/api/alert-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/candidates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/candidates/[id]">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/candidates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/reviews">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/sessions/[id]/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/sessions/[id]/analyze">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/sessions/[id]/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/sessions/[id]/ib-validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/sessions/[id]/ib-validate">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/sessions/[id]/ib-validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/sessions/[id]/llm-result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/sessions/[id]/llm-result">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/sessions/[id]/llm-result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/contest/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contest/sessions">> = Specific
  const handler = {} as typeof import("../../../../app/api/contest/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/chart-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/chart-analysis">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/chart-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/check-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-alerts">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/check-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/contest-review-kr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/contest-review-kr">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/contest-review-kr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/contest-review-us/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/contest-review-us">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/contest-review-us/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/daily-screeners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-screeners">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/daily-screeners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/edgar-backfill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/edgar-backfill">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/edgar-backfill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/purge-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/purge-metrics">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/purge-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/recommendation-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/recommendation-performance">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/recommendation-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/recommendation-weekly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/recommendation-weekly">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/recommendation-weekly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/rs-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/rs-metrics">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/rs-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/cron/snapshot-market-state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/snapshot-market-state">> = Specific
  const handler = {} as typeof import("../../../../app/api/cron/snapshot-market-state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/local-analysis/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-analysis/jobs">> = Specific
  const handler = {} as typeof import("../../../../app/api/local-analysis/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/local-analysis/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-analysis/status">> = Specific
  const handler = {} as typeof import("../../../../app/api/local-analysis/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/local-llm-proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-llm-proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../../../app/api/local-llm-proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/macro/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/macro/history">> = Specific
  const handler = {} as typeof import("../../../../app/api/macro/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/macro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/macro">> = Specific
  const handler = {} as typeof import("../../../../app/api/macro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/market-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-data">> = Specific
  const handler = {} as typeof import("../../../../app/api/market-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/master-filter/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/master-filter/history">> = Specific
  const handler = {} as typeof import("../../../../app/api/master-filter/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/master-filter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/master-filter">> = Specific
  const handler = {} as typeof import("../../../../app/api/master-filter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance">> = Specific
  const handler = {} as typeof import("../../../../app/api/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/portfolio/risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolio/risk">> = Specific
  const handler = {} as typeof import("../../../../app/api/portfolio/risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/portfolio/risk/what-if/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolio/risk/what-if">> = Specific
  const handler = {} as typeof import("../../../../app/api/portfolio/risk/what-if/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/price-history/[ticker]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/price-history/[ticker]">> = Specific
  const handler = {} as typeof import("../../../../app/api/price-history/[ticker]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/recommendations/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations/diagnostics">> = Specific
  const handler = {} as typeof import("../../../../app/api/recommendations/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/recommendations/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations/metrics">> = Specific
  const handler = {} as typeof import("../../../../app/api/recommendations/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations">> = Specific
  const handler = {} as typeof import("../../../../app/api/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/recommendations/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations/summary">> = Specific
  const handler = {} as typeof import("../../../../app/api/recommendations/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources">> = Specific
  const handler = {} as typeof import("../../../../app/api/resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/saved-screens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saved-screens">> = Specific
  const handler = {} as typeof import("../../../../app/api/saved-screens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/batch">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/canslim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/canslim">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/canslim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/leader/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/leader">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/leader/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/metrics">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/momentum/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/momentum">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/momentum/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/qullamaggie/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/qullamaggie">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/qullamaggie/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/reversal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/reversal">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/reversal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/snapshots">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/telegram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/telegram">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/telegram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/scanner/universe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/universe">> = Specific
  const handler = {} as typeof import("../../../../app/api/scanner/universe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/security-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-events">> = Specific
  const handler = {} as typeof import("../../../../app/api/security-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/security-lookup/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-lookup/batch">> = Specific
  const handler = {} as typeof import("../../../../app/api/security-lookup/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/security-lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-lookup">> = Specific
  const handler = {} as typeof import("../../../../app/api/security-lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/security-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-search">> = Specific
  const handler = {} as typeof import("../../../../app/api/security-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/telegram-webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telegram-webhook">> = Specific
  const handler = {} as typeof import("../../../../app/api/telegram-webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/test-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-report">> = Specific
  const handler = {} as typeof import("../../../../app/api/test-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/test/telegram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/telegram">> = Specific
  const handler = {} as typeof import("../../../../app/api/test/telegram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/toss-proxy/holdings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/toss-proxy/holdings">> = Specific
  const handler = {} as typeof import("../../../../app/api/toss-proxy/holdings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trade-executions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trade-executions">> = Specific
  const handler = {} as typeof import("../../../../app/api/trade-executions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trade-exit-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trade-exit-rules">> = Specific
  const handler = {} as typeof import("../../../../app/api/trade-exit-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trade-stop-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trade-stop-events">> = Specific
  const handler = {} as typeof import("../../../../app/api/trade-stop-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades">> = Specific
  const handler = {} as typeof import("../../../../app/api/trades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/watchlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/watchlist">> = Specific
  const handler = {} as typeof import("../../../../app/api/watchlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
