import type { CanslimScannerResult, ContestPromptCandidate, ScannerResult } from '@/types';

export function minerviniCandidateFromResult(item: ScannerResult, rank: number): ContestPromptCandidate {
  return {
    screener_source: 'minervini',
    ticker: item.ticker,
    exchange: item.exchange,
    name: item.name || item.ticker,
    user_rank: rank,
    recommendation_tier: item.recommendationTier,
    recommendation_reason: item.recommendationReason,
    exception_signals: item.exceptionSignals || [],
    rs_rating: item.rsRating ?? null,
    internal_rs_rating: item.internalRsRating ?? null,
    external_rs_rating: item.externalRsRating ?? null,
    rs_rank: item.rsRank ?? null,
    rs_universe_size: item.rsUniverseSize ?? null,
    rs_percentile: item.rsPercentile ?? null,
    weighted_momentum_score: item.weightedMomentumScore ?? null,
    ibd_proxy_score: item.ibdProxyScore ?? null,
    mansfield_rs_flag: item.mansfieldRsFlag ?? null,
    mansfield_rs_score: item.mansfieldRsScore ?? null,
    rs_data_quality: item.rsDataQuality ?? 'NA',
    macro_action_level: item.macroActionLevel ?? null,
    benchmark_relative_score: item.benchmarkRelativeScore ?? null,
    rs_line_new_high: item.rsLineNewHigh ?? null,
    rs_line_near_high: item.rsLineNearHigh ?? null,
    tennis_ball_count: item.tennisBallCount ?? null,
    tennis_ball_score: item.tennisBallScore ?? null,
    return_3m: item.return3m ?? null,
    return_6m: item.return6m ?? null,
    return_9m: item.return9m ?? null,
    return_12m: item.return12m ?? null,
    base_type: item.baseType ?? null,
    momentum_branch: item.momentumBranch ?? null,
    eight_week_return_pct: item.eightWeekReturnPct ?? null,
    distance_from_ma50_pct: item.distanceFromMa50Pct ?? null,
    low_52_week_advance_pct: item.low52WeekAdvancePct ?? null,
    high_tight_flag: item.highTightFlag ?? null,
    sepa_status: item.sepaStatus,
    sepa_passed: item.sepaPassed,
    sepa_failed: item.sepaFailed,
    vcp_status: item.vcpGrade,
    vcp_score: item.vcpScore,
    contraction_score: item.contractionScore ?? null,
    volume_dry_up_score: item.volumeDryUpScore ?? null,
    bb_squeeze_score: item.bbSqueezeScore ?? null,
    pocket_pivot_score: item.pocketPivotScore ?? null,
    pivot_price: item.pivotPrice,
    pivot_date: item.pivotDate ?? null,
    pivot_age_days: item.pivotAgeDays ?? null,
    pivot_kind: item.pivotKind ?? null,
    reference_high_price: item.referenceHighPrice ?? null,
    reference_high_date: item.referenceHighDate ?? null,
    distance_to_pivot_pct: item.distanceToPivotPct,
    avg_dollar_volume: item.sepaEvidence?.metrics.avgDollarVolume20 || null,
    price: item.currentPrice,
    price_as_of: item.priceAsOf,
    source: item.priceSource || 'MTN Minervini scanner',
    provider_attempts: item.providerAttempts || [],
  };
}

export function canslimCandidateFromResult(item: CanslimScannerResult, rank: number): ContestPromptCandidate {
  return {
    screener_source: 'canslim',
    ticker: item.ticker,
    exchange: item.exchange,
    name: item.name || item.ticker,
    user_rank: rank,
    recommendation_tier: item.dualTier === 'TIER_1' ? 'Recommended' : item.dualTier === 'EXCLUDED' ? 'Low Priority' : 'IB Review',
    recommendation_reason: `CANSLIM ${item.dualTier}; confidence ${item.canslimResult.confidence}; ${item.canslimResult.pass ? '7-pillar pass' : `failed ${item.canslimResult.failedPillar || 'pillar'}`}`,
    exception_signals: item.dataWarnings || [],
    rs_rating: item.rsRating ?? null,
    internal_rs_rating: null,
    external_rs_rating: item.rsSource === 'DB_BATCH' ? item.rsRating ?? null : null,
    rs_rank: null,
    rs_universe_size: null,
    rs_percentile: null,
    weighted_momentum_score: null,
    ibd_proxy_score: null,
    mansfield_rs_flag: item.mansfieldRsFlag ?? null,
    mansfield_rs_score: item.mansfieldRsScore ?? null,
    rs_data_quality: item.rsSource ? 'OK' : 'NA',
    macro_action_level: null,
    benchmark_relative_score: item.benchmarkRelativeScore ?? null,
    rs_line_new_high: null,
    rs_line_near_high: null,
    tennis_ball_count: null,
    tennis_ball_score: null,
    return_3m: null,
    return_6m: null,
    return_9m: null,
    return_12m: null,
    base_type: item.basePattern?.type === 'VCP' ? 'Standard_VCP' : null,
    momentum_branch: null,
    eight_week_return_pct: null,
    distance_from_ma50_pct: null,
    low_52_week_advance_pct: null,
    high_tight_flag: null,
    sepa_status: item.canslimResult.pass ? 'pass' : 'fail',
    sepa_passed: item.canslimResult.pillarDetails.filter((pillar) => pillar.status === 'PASS').length,
    sepa_failed: item.canslimResult.pillarDetails.filter((pillar) => pillar.status === 'FAIL').length,
    vcp_status: item.vcpGrade,
    vcp_score: item.vcpScore,
    contraction_score: null,
    volume_dry_up_score: null,
    bb_squeeze_score: null,
    pocket_pivot_score: null,
    pivot_price: item.basePattern?.pivotPoint ?? null,
    pivot_date: null,
    pivot_age_days: null,
    pivot_kind: item.basePattern?.type === 'VCP' ? 'VCP_PIVOT' : null,
    reference_high_price: null,
    reference_high_date: null,
    distance_to_pivot_pct: item.currentPrice && item.basePattern?.pivotPoint
      ? Number((((item.currentPrice - item.basePattern.pivotPoint) / item.basePattern.pivotPoint) * 100).toFixed(2))
      : null,
    avg_dollar_volume: null,
    price: item.currentPrice,
    price_as_of: item.analyzedAt,
    source: "MTN O'Neil CANSLIM scanner",
    provider_attempts: [],
    canslim: {
      pass: item.canslimResult.pass,
      confidence: item.canslimResult.confidence,
      failed_pillar: item.canslimResult.failedPillar,
      n_status: item.canslimResult.nStatus,
      stop_loss_price: item.canslimResult.stopLossPrice,
      dual_tier: item.dualTier,
      base_pattern: item.basePattern,
      pillars: item.canslimResult.pillarDetails,
      data_sources: item.dataSources ?? null,
      analysis_coverage: item.analysisCoverage ?? null,
    },
  };
}
